// Display metadata only; option values always retain the backend protocol ID.
const protocols: Record<string, { label: string; brand: string; annotation?: string }> = {
  openai_chat: { label: 'OpenAI Chat', brand: 'OpenAI' },
  openai_chat_completions: { label: 'OpenAI Chat Completions', brand: 'OpenAI' },
  openai_responses: { label: 'OpenAI Responses', brand: 'OpenAI' },
  openai_codex_responses: { label: 'OpenAI Codex Responses', brand: 'OpenAI', annotation: 'OpenAI Responses' },
  openai_images: { label: 'OpenAI Images', brand: 'OpenAI' },
  openai_models: { label: 'OpenAI Models', brand: 'OpenAI' },
  anthropic_messages: { label: 'Anthropic Messages', brand: 'Anthropic' },
  bedrock_converse_stream: { label: 'AWS Bedrock Converse Stream', brand: 'AWS Bedrock' },
  google_generate_content: { label: 'Google Gemini Generate Content', brand: 'Google Gemini' },
  google_interactions: { label: 'Google Gemini Interactions', brand: 'Google Gemini' },
  google_vertex_generate_content: { label: 'Google Vertex AI Generate Content', brand: 'Google Gemini' },
  mistral_conversations: { label: 'Mistral Conversations', brand: 'Mistral' },
  deepseek_chat: { label: 'DeepSeek Chat', brand: 'DeepSeek', annotation: 'OpenAI Chat' },
  deepseek_responses: { label: 'DeepSeek Responses', brand: 'DeepSeek', annotation: 'OpenAI Responses' },
  deepseek_messages: { label: 'DeepSeek Messages', brand: 'DeepSeek', annotation: 'Anthropic Messages' },
  zai_chat: { label: 'Z.AI Chat', brand: 'Z.AI', annotation: 'OpenAI Chat' },
  zai_messages: { label: 'Z.AI Messages', brand: 'Z.AI', annotation: 'Anthropic Messages' },
  zai_images: { label: 'Z.AI Images', brand: 'Z.AI', annotation: 'OpenAI Images' },
  kimi: { label: 'Kimi', brand: 'Kimi', annotation: 'OpenAI Chat' },
  qwen_chat: { label: 'Qwen Chat', brand: 'Qwen', annotation: 'OpenAI Chat' },
  qwen_responses: { label: 'Qwen Responses', brand: 'Qwen', annotation: 'OpenAI Responses' },
  mimo_chat: { label: 'MiMo Chat', brand: 'MiMo', annotation: 'OpenAI Chat' },
  mimo_responses: { label: 'MiMo Responses', brand: 'MiMo', annotation: 'OpenAI Responses' },
  mimo_messages: { label: 'MiMo Messages', brand: 'MiMo', annotation: 'Anthropic Messages' },
  minimax_chat: { label: 'MiniMax Chat', brand: 'MiniMax', annotation: 'OpenAI Chat' },
  minimax_messages: { label: 'MiniMax Messages', brand: 'MiniMax', annotation: 'Anthropic Messages' },
  hunyuan_chat: { label: 'Tencent Hunyuan Chat', brand: 'Tencent Hunyuan (TokenHub)', annotation: 'OpenAI Chat' },
};
export const protocolPresentation = (id: string) => protocols[id] ?? { label: id, brand: '' };
