// UI explanations of the current wish-config schema. Keep semantics aligned
// with schema.rs, schema/providerd.rs and the owning runtime; validation stays
// on the daemons. Path-specific copy takes precedence over shared field names.
type Help = readonly [zh: string, en: string];
const fields: Record<string, Help> = {
  data_dir: ['后端保存会话和资源的绝对目录。更改目录不会自动搬迁已有数据。', 'Absolute directory for session data and resources; changing it does not move existing data.'],
  wishd: ['管理会话服务的连接、身份验证和新会话默认值。', 'Configure session-service connections, authentication and defaults for new sessions.'],
  streaming: ['控制回复生成时是否持续向客户端推送内容。', 'Control live delivery of replies while they are being generated.'],
  agent: ['控制一次模型回复的大小，以及同一轮中的工具执行方式。', 'Set reply size limits and how tools run within one assistant turn.'],
  retry: ['设置模型请求失败后的再次尝试和故障暂停策略。', 'Configure model-request retries and circuit breaking.'],
  queue: ['限制待处理消息和同时运行的会话，控制资源占用。', 'Bound queued messages and active sessions to control resource use.'],
  stateless: ['用会话上下文发起独立查询，不把查询结果追加到原会话。', 'Query a session context independently without appending the result to that session.'],
  compaction: ['将较早的上下文整理为 Summary，为后续对话腾出模型容量。', 'Summarize earlier context to make room for subsequent conversation.'],
  shell: ['设置模型执行Shell 命令时使用的程序、等待时间和输入输出限制。', 'Configure the shell used by tools, execution waits and input/output limits.'],
  attachments: ['限制普通文件附件的体积和数量，图片使用独立的图片上传限制。', 'Limit file attachment sizes and counts. Images use the separate image upload limits.'],
  max_attachment_bytes: ['单个普通附件允许上传的最大 Byte 数。附件按二进制保存，模型收到文件名和本地路径。', 'Maximum bytes per file attachment. Files are stored as binary blobs; the model receives the filename and local path.'],
  max_attachments_per_message: ['一条消息最多附带的普通文件数量，不包含图片。', 'Maximum file attachments per message, excluding images.'],
  images: ['限制消息中上传图片的格式、体积和数量。', 'Limit the formats, sizes and counts of images attached to messages.'],
  image_jobs: ['设置生成或编辑图片任务的默认行为及数量限制。', 'Set defaults and output limits for image generation and editing jobs.'],
  context_json: ['限制通过 JSON 导入或导出的上下文 Entry 数量。', 'Limit entries in context JSON imports and exports.'],
  context_measurement: ['测量将要发送给模型的上下文用量，判断是否接近容量上限。', 'Measure model-input context usage and detect when it approaches capacity.'],
  context_read: ['设置历史记录读取、定位窗口和预览内容的大小。', 'Configure history pages, anchored windows and preview lengths.'],
  account_observation: ['从已配置的账户来源查询余额或用量，并保留历史快照。', 'Read balance or usage from configured account sources and retain snapshots.'],
  storage: ['控制会话的内存缓存和闲置时的磁盘压缩。', 'Control session memory caching and disk compression while idle.'],
  leases: ['确保同一会话的写入由持有有效租约的进程负责。', 'Allow session writes only while a process holds a valid writer lease.'],
  events: ['设置服务事件的心跳和客户端缓冲区。', 'Configure service-event heartbeats and subscriber buffers.'],
  status: ['设置状态列表接口的默认顺序和每页数量。', 'Set default ordering and page sizes for status collections.'],
  diagnostics: ['控制诊断包的生成、大小及保留时间。', 'Control diagnostic bundle creation, size and retention.'],
  idempotency: ['保留请求去重记录，避免同一个请求被重复执行。', 'Retain idempotency records to avoid executing the same request twice.'],
  logging: ['控制后端日志的详细程度。', 'Control backend log verbosity.'],
  listen: ['后端进程绑定的网络地址；更改后需要重启对应服务。', 'Network address bound by the daemon; changes require restarting that service.'],
  host: ['127.0.0.1 仅供本机连接；0.0.0.0 监听所有 IPv4 网卡。', '127.0.0.1 accepts local connections only; 0.0.0.0 listens on every IPv4 interface.'],
  port: ['该后端监听的端口；连接它的客户端也需要使用相同端口。', 'The port this daemon listens on; its clients must use the same port.'],
  allow_insecure_remote: ['允许在未启用令牌验证时监听非本机地址；不会关闭已经启用的令牌验证。', 'Permit a non-loopback listener without token authentication; existing token authentication is not disabled.'],
  bearer_token: ['wishd 连接模型服务时发送的令牌，需与模型服务的访问令牌一致。', 'Token wishd sends to the provider service; it must match that service’s token.'],
  provider_client: ['wishd 到 wish-providerd 的内部连接，不是模型厂商的 API 地址。', 'The connection from wishd to wish-providerd, not the model vendor’s API.'],
  base_url: ['填写完整的 HTTP 或 HTTPS 服务地址，请求路径单独配置。', 'Enter the full HTTP or HTTPS service base URL; configure the request path separately.'],
  http: ['控制客户端请求大小及长连接的心跳间隔。', 'Control client request limits and long-lived connection heartbeats.'],
  connect_timeout_ms: ['建立连接最多等待多久；超时后请求报错。', 'Maximum time to establish a connection before the request fails.'],
  total_timeout_ms: ['一次请求从开始到结束的最长时间，包括流式输出。', 'Maximum duration of an entire request, including streamed output.'],
  stream_read_timeout_ms: ['wishd 等待模型服务下一段响应的最长时间；通常应高于模型服务的流式空闲超时。', 'Maximum wait for the next provider-service response chunk; normally longer than its upstream idle timeout.'],
  max_json_body_bytes: ['后端接受的单次 JSON 请求体大小，超过上限会拒绝请求。', 'Maximum JSON request body accepted by this daemon; larger requests are rejected.'],
  default_model: ['创建会话时未指定模型才使用这些值；已有会话不受影响。', 'Used when creating a session without an explicit model; existing sessions keep their model.'],
  provider: ['填写模型服务中配置的提供商标识名称。', 'The provider instance ID configured in the provider service.'],
  model: ['填写提供商接受的模型名称。', 'A model ID accepted by the selected provider.'],
  reasoning_effort: ['设置新会话默认的推理强度；可用等级取决于模型。移除此项则不指定。', 'Default reasoning effort for new sessions; supported levels depend on the model. Remove to leave unspecified.'],
  max_assistant_message_bytes: ['限制一次模型响应序列化后的大小，包含正文、思考内容和工具调用参数；接收完成后检查，超限则报错。', 'Limit the serialized size of one model response, including text, reasoning and tool-call arguments. Checked after reception; oversized responses fail.'],
  unknown_tool_is_fatal: ['开启时，模型调用未知工具会终止运行；关闭时将错误反馈给模型继续处理。', 'Stop the run on an unknown tool, or return a tool error to the model and continue when disabled.'],
  tool_execution: ['并行执行同一轮中的多个工具可减少等待；依次执行则按调用顺序运行。', 'Parallel runs tools from the same turn concurrently; serial runs them in call order.'],
  max_attempts: ['一次操作的最多尝试次数，包含第一次尝试；1 表示失败后不再重试。', 'Total attempts for an operation, including the first; 1 disables retries.'],
  initial_delay_ms: ['第一次失败后，再次尝试前的基础等待时间。', 'Base delay after the first failure before retrying.'],
  max_delay_ms: ['重试等待时间的上限，不能小于首次重试等待时间。', 'Upper bound on retry delay; must be at least the initial delay.'],
  multiplier: ['每次重试将基础等待时间乘以此值；1 表示不递增。', 'Multiply the base delay by this value on each retry; 1 keeps it constant.'],
  jitter_ratio: ['给等待时间增加随机浮动，避免多个请求同时重试；0 关闭浮动，取值 0–1。', 'Randomize retry delays to spread requests; 0 disables jitter. Range: 0–1.'],
  circuit_breaker: ['错误达到阈值后暂时停止请求，等待后用少量请求探测服务是否恢复。', 'Pause requests after enough failures, then probe for recovery with a limited number of requests.'],
  minimum_samples: ['积累到此数量的请求结果后，才按失败比例判断是否暂停。', 'Minimum number of request results before evaluating the failure ratio.'],
  failure_ratio: ['失败请求占比达到此值时暂停请求；例如 0.5 表示 50%。', 'Pause when the failure fraction reaches this threshold; 0.5 means 50%.'],
  sample_window_ms: ['只用这个时间段内的请求结果计算失败比例。', 'Use request outcomes within this window to calculate the failure ratio.'],
  open_ms: ['触发故障暂停后，等待多久再尝试恢复探测。', 'Wait this long after opening the circuit before probing for recovery.'],
  half_open_max_probes: ['恢复探测阶段允许尝试的请求数量。', 'Number of requests allowed during recovery probing.'],
  max_open_ms: ['限制故障暂停阶段的最长持续时间。', 'Upper bound on the circuit’s open duration.'],
  max_depth_per_session: ['每个会话最多积压多少条待处理消息。', 'Maximum pending messages in a single session.'],
  max_delivery_bytes: ['限制一条送入队列的消息大小。', 'Maximum size of one delivery entering the queue.'],
  max_pending_content_bytes_per_session: ['限制同一会话全部排队消息的内容总大小。', 'Maximum combined content size of pending messages in one session.'],
  max_active_sessions: ['最多同时推进多少个会话的运行；其余会话等待调度。', 'Maximum sessions running concurrently; others wait to be scheduled.'],
  scheduler_fallback_poll_ms: ['未收到新消息通知时，调度器检查待运行会话的补充间隔。', 'Fallback scan interval for runnable sessions when no enqueue notification arrives.'],
  max_concurrent_requests: ['整个服务同时处理的独立上下文查询数量上限。', 'Maximum independent context queries running across the service.'],
  max_concurrent_requests_per_session: ['来自同一源会话的独立查询最多同时运行多少个。', 'Maximum concurrent independent queries using the same source session.'],
  result_memory_grace_s: ['独立查询完成后，在内存中保留结果供读取的时间。', 'How long completed independent-query results remain readable in memory.'],
  trigger_ratio: ['上下文占模型容量的比例达到此值时触发压缩；例如 0.8 表示 80%。', 'Compact when context reaches this fraction of model capacity; 0.8 means 80%.'],
  reserve_tokens: ['压缩后为后续输入和输出预留的模型容量。', 'Capacity reserved after compaction for subsequent input and output.'],
  worker_interval_ms: ['后台协调器检查上下文压缩工作的频率。', 'How often the background coordinator checks compaction work.'],
  max_concurrent_sessions: ['限制同时进行上下文压缩的会话数量。', 'Maximum sessions whose context can be compacted concurrently.'],
  failure_retry_ms: ['准备备用上下文失败后，等待多久再次尝试。', 'Delay before retrying a failed standby-context preparation.'],
  segment_lower_tokens: ['助手和工具片段小于此值时，在下条系统或用户消息到达后保留原文。', 'Assistant/tool spans below this size stay verbatim when the next system or user message arrives.'],
  segment_upper_tokens: ['助手和工具片段达到此大小时立即生成 Summary。', 'Summarize assistant/tool spans immediately once they reach this size.'],
  max_verbatim_message_tokens: ['系统或用户消息超过此大小时，允许用 Summary 替换原文。', 'System or user messages larger than this may be replaced by summaries.'],
  standby_target_ratio: ['备用上下文超过模型容量的此比例时重新分段压缩；0.5 表示 50%。', 'Repartition prepared context above this fraction of capacity; 0.5 means 50%.'],
  repartition_parts: ['重新分段时分成多少个近似等大的片段，至少为 2。', 'Number of roughly equal parts when repartitioning; at least 2.'],
  min_summary_bytes: ['Summary 短于此值会被视为无效结果。', 'Reject summaries shorter than this size.'],
  max_summary_bytes: ['限制一段 Summary 的文本大小。', 'Maximum text size of an individual summary.'],
  summary_max_output_tokens: ['向模型请求 Summary 时允许输出的最多 Token 数。', 'Maximum output tokens requested for a summary.'],
  boundary_excerpt_chars: ['Summary 提示词中，每个片段边界最多带入多少字符。', 'Maximum characters from each span boundary included in the summary prompt.'],
  image_estimated_tokens: ['缺少精确用量时，用于估算每张图片的 Token 开销。', 'Estimated token cost per image when exact counts are unavailable.'],
  fallback_bytes_per_token: ['无法精确计数时，用文本 Byte 数除以此值估算 Token 数。', 'Estimate tokens by dividing text bytes by this value when exact counting is unavailable.'],
  command: ['指定Shell 程序及启动参数，参数中必须有一个 {command} 占位符。', 'Choose the shell executable and arguments, containing exactly one {command} placeholder.'],
  kind: ['Shell 程序的类型，例如 bash、zsh 或 powershell。', 'The shell family, such as bash, zsh or powershell.'],
  program: ['后端机器上Shell 程序的绝对路径，例如 /bin/bash。', 'Absolute path to the shell executable on the backend machine, such as /bin/bash.'],
  args: ['按顺序传给Shell 程序的启动参数；{command} 会替换为要执行的命令。', 'Ordered shell arguments; {command} is replaced by the command to execute.'],
  default_soft_timeout_s: ['前台最多等待多久；超过后转为后台执行，不会因此杀死命令。', 'How long to wait in the foreground before returning a background execution; does not kill the command.'],
  kill_grace_ms: ['发出终止信号后等待多久，再强制杀死仍未退出的进程。', 'Grace after a termination signal before force-killing a process that has not exited.'],
  interrupt_kill_grace_ms: ['中断会话时，前台命令收到终止信号后的强制结束等待时间。', 'Grace before force-killing a foreground command during session interruption.'],
  inline_output_bytes: ['工具结果中直接附带的输出大小；更多输出可继续读取。', 'Output included directly in a tool result; additional output can be read later.'],
  poll_default_bytes: ['读取执行输出时，未指定大小所使用的默认值。', 'Default output read size when the caller does not specify one.'],
  poll_max_bytes: ['单次读取最多返回多少执行输出。', 'Maximum execution output returned by one read.'],
  poll_max_wait_ms: ['读取执行输出时，最多等待新输出多久。', 'Maximum time an output read may wait for new data.'],
  reconcile_interval_s: ['后台核对命令执行状态的时间间隔。', 'Interval for reconciling command execution state.'],
  background_notifications: ['控制后台命令结束时发送给会话的通知。', 'Configure notifications sent to a session when a background command finishes.'],
  wake_session_on_terminal: ['后台命令结束后，唤醒空闲会话继续处理结果。', 'Wake an idle session to process a background command’s completion.'],
  max_command_bytes: ['允许执行的单条命令大小上限。', 'Maximum size of a command submitted for execution.'],
  max_rendered_bytes: ['限制生成的后台执行通知大小。', 'Maximum rendered size of a background execution notification.'],
  limits: ['限制命令输入输出的总量，超出限制会明确报错。', 'Bound command input and output; exceeding a limit reports an error.'],
  max_stdin_write_bytes: ['一次向运行中命令写入的输入大小上限。', 'Maximum input sent to a running command in a single write.'],
  stdin_write_timeout_ms: ['一次输入写入最多等待多久，超时后报告写入失败。', 'Maximum duration of one input write before reporting a timeout.'],
  max_stdin_total_bytes: ['同一次命令执行累计接收的输入总大小上限。', 'Maximum cumulative input accepted by one execution.'],
  max_output_bytes_per_execution: ['同一次命令执行可以保存的输出总大小上限。', 'Maximum output retained for a single execution.'],
  allowed_mime_types: ['每项填写一个 MIME 类型，例如 image/png；列表外的图片格式会被拒绝。', 'One MIME type per entry, such as image/png; unlisted image formats are rejected.'],
  max_image_bytes: ['单张上传图片的最大文件大小。', 'Maximum file size of one uploaded image.'],
  max_images_per_message: ['一条消息最多附带多少张图片。', 'Maximum images attached to a single message.'],
  default_kind: ['未指定操作时使用生成新图片，或编辑已有图片。', 'Default operation when unspecified: generate a new image or edit an existing one.'],
  default_output_images: ['未指定数量时，图片任务默认请求的输出张数。', 'Number of output images requested when a job omits the count.'],
  max_output_images: ['一个图片任务最多允许请求多少张输出图片。', 'Maximum output images requested by a single job.'],
  max_entries: ['单次上下文 JSON 导入或导出的 Entry 数量上限。', 'Maximum entries in one context JSON import or export.'],
  automatic_before_model_call: ['每次调用模型前测量输入用量；关闭后仍可手动测量。', 'Measure input usage before every model call; manual measurement remains available when disabled.'],
  near_limit_ratio: ['达到模型容量的此比例时标记为接近上限；例如 0.9 表示 90%。', 'Mark usage near capacity at this fraction; 0.9 means 90%.'],
  default_direction: ['未指定读取方向时，从最新消息向前读，或从最早消息向后读。', 'Default history direction: backward from newest, or forward from oldest.'],
  default_page_items: ['请求未指定数量时，每页返回的 Entry 数。', 'Entries per page when a request omits the limit.'],
  max_page_items: ['客户端单次分页请求可指定的最大 Entry 数。', 'Maximum page size a client can request.'],
  default_window_before: ['定位某条历史记录时，默认同时读取它之前的 Entry 数。', 'Default entries before an anchored history item.'],
  default_window_after: ['定位某条历史记录时，默认同时读取它之后的 Entry 数。', 'Default entries after an anchored history item.'],
  max_window_items: ['限制一次定位窗口中返回的总 Entry 数。', 'Maximum entries returned in one anchored window.'],
  preview_text_bytes: ['列表预览中保留的正文大小；完整内容仍可单独读取。', 'Text retained in list previews; full content remains separately readable.'],
  preview_reasoning_bytes: ['列表预览中保留的思考内容大小。', 'Reasoning text retained in list previews.'],
  preview_tool_arguments_bytes: ['列表预览中保留的工具参数大小。', 'Tool arguments retained in list previews.'],
  preview_tool_result_bytes: ['列表预览中保留的工具结果大小。', 'Tool result content retained in list previews.'],
  change_feed_default_items: ['增量同步未指定数量时，一次返回多少条变更。', 'Default changes returned per incremental-sync request.'],
  change_feed_max_items: ['一次增量同步最多返回多少条变更。', 'Maximum changes returned per incremental-sync request.'],
  min_refresh_interval_ms: ['账户用量查询之间的最短等待时间，防止过于频繁地请求上游。', 'Minimum interval between account-usage refreshes.'],
  max_history_snapshots_per_source: ['每个用量来源最多保留多少份历史快照。', 'Maximum historical snapshots retained per usage source.'],
  history_default_items: ['查询账户用量历史时，默认返回多少份快照。', 'Default snapshot count returned by account-usage history queries.'],
  bindings: ['给账户命名并引用其凭据，供用量来源使用。', 'Name accounts and reference credentials for usage sources.'],
  sources: ['把账户、服务端点和查询协议组合为一个用量来源。', 'Combine an account, endpoint and observation protocol into a usage source.'],
  id: ['其他配置引用此项目时使用的唯一名称。', 'Unique name used to reference this entry from other settings.'],
  display_name: ['在界面中展示的名称，便于区分账户或模型。', 'A readable name for identifying the account or model in the interface.'],
  credential: ['引用后端进程环境变量中的账户凭据。', 'Reference account credentials from the backend process environment.'],
  account_binding: ['填写账户绑定中已有的标识名称。', 'ID of an existing account binding.'],
  method: ['按目标接口要求选择 HTTP 请求方法。', 'HTTP method required by the target API.'],
  path: ['相对于服务地址的请求路径，以 / 开头。', 'Request path relative to the service base URL, starting with /.'],
  fresh_for_ms: ['快照在这段时间内视为新数据。', 'Duration for which a snapshot is considered fresh.'],
  stale_for_ms: ['快照超过此时间后标记为过期。', 'Age after which a snapshot is marked stale.'],
  request_timeout_ms: ['一次账户用量查询的最长等待时间。', 'Maximum duration of one account-usage request.'],
  session_cache_memory_budget_bytes: ['按已提交 JSON 数据大小控制会话缓存预算，并非整个进程的内存上限。', 'Session cache budget measured in committed JSON bytes, not a process-wide memory limit.'],
  cold: ['闲置会话的数据库可压缩存储，再次使用时恢复；不会删除对话。', 'Compress idle session databases and restore them when used again; conversations are retained.'],
  idle_after_ms: ['会话持续闲置多久后可以压缩存储。', 'Continuous inactivity required before a session can be compressed.'],
  zstd_level: ['更高的压缩级别通常节省磁盘，但需要更多压缩时间。', 'Higher compression levels generally save disk space at the cost of more CPU time.'],
  session_writer_ttl_ms: ['写入者未续期超过此时间后租约失效。', 'A writer lease expires if it is not renewed within this duration.'],
  session_writer_heartbeat_ms: ['写入者多久续期一次；必须短于租约有效时间。', 'Writer renewal interval; must be shorter than the lease lifetime.'],
  sse_heartbeat_ms: ['无业务事件时发送心跳的间隔，帮助客户端保持连接。', 'Heartbeat interval when no business events are sent, keeping clients connected.'],
  subscriber_buffer_events: ['为每个订阅者暂存多少个待发送事件。', 'Maximum pending events buffered for each subscriber.'],
  max_subscribers_per_stream: ['同一个回复流最多允许多少个客户端同时订阅。', 'Maximum clients subscribed to the same reply stream.'],
  default_order: ['状态列表默认按时间从新到旧或从旧到新排列。', 'Default chronological ordering of status collections.'],
  bundle_enabled: ['允许通过诊断接口创建问题排查包。', 'Allow diagnostic bundles to be created through the diagnostics API.'],
  bundle_retention_s: ['诊断包生成后保留多久，再纳入清理。', 'How long generated diagnostic bundles are retained before cleanup.'],
  bundle_max_bytes: ['一个诊断包允许占用的最大空间。', 'Maximum size of a diagnostic bundle.'],
  retention_s: ['同一请求标识的去重记录保留多久。', 'How long idempotency records for request keys are retained.'],
  level: ['info 记录常规运行信息；debug、trace 提供更详细的排查信息；off 关闭日志。', 'info records normal operation; debug and trace add detail; off disables logging.'],
  proxy: ['集中定义可复用的代理策略，供提供商和图片下载引用。', 'Define reusable proxy policies for providers and image downloads.'],
  upstream: ['限制模型服务访问厂商 API 时的等待时间和响应大小。', 'Bound waits and response sizes when the provider service calls vendor APIs.'],
  providers: ['使用内置预设，或直接配置提供商的服务地址和连接选项。', 'Use a preset or configure the provider’s service address and connection options directly.'],
  endpoints: ['定义可以被其他配置引用的服务地址及连接方式。', 'Define service addresses and connection details referenced by other settings.'],
  model_catalog_cache_ttl_s: ['模型列表在内存中的有效时间，过期后重新读取。', 'How long model catalogs remain valid in memory before being fetched again.'],
  preset: ['预设提供厂商地址、协议和认证方式的默认值，可在高级设置中覆盖。', 'A preset supplies default addresses, protocols and authentication; advanced settings can override them.'],
  endpoint: ['引用服务端点配置的标识名称，不是 URL。端点配置定义 API 基础地址和连接选项；使用自定义端点时需清空预设。', 'Reference an endpoint by ID; a provider using a custom endpoint must leave its preset empty.'],
  protocol: ['选择目标接口实际支持的通信协议，同一地址可以使用不同协议。', 'Choose the protocol the target API supports; the same address can support different protocols.'],
  api_key: ['未编辑时保留现有密钥；输入新值可替换，也支持 ${环境变量名称}。清空请使用“清空”按钮。', 'Untouched fields keep the current key. Enter a replacement or an ${ENV_VAR} reference; use Clear to remove it.'],
  credentials: ['填写预设额外需要的命名凭据，例如 workspace_id。', 'Named credentials additionally required by a preset, such as workspace_id.'],
  allow_any_model: ['开启后接受模型列表及模型配置之外的名称；实际是否可调用仍由上游决定。', 'Accept IDs absent from both catalog and overrides; the upstream still decides whether they are callable.'],
  model_id_max_bytes: ['限制客户端提交的模型名称长度。', 'Maximum length of model IDs submitted by clients.'],
  models: ['按模型名称配置容量和能力，填写的值优先于模型列表中的数据。', 'Override capacity and capabilities by model ID; entered values take precedence over catalog metadata.'],
  compat: ['覆盖提供商协议的具体请求或响应格式；未添加的选项使用协议默认值。', 'Override provider wire-format options; omitted fields use protocol defaults.'],
  input_count: ['选择发送请求前计算输入 Token 的方式。', 'Choose how input tokens are counted before invocation.'],
  dialect: ['控制命名协议扩展允许哪些覆盖项。', 'Control permitted overrides for a named protocol dialect.'],
  context_window_tokens: ['覆盖模型可容纳的上下文 Token 数；必须大于 0，应填写模型的实际容量。', 'Override context capacity in tokens; must be positive and reflect the model’s real capacity.'],
  max_output_tokens: ['覆盖模型允许的最大输出 Token 数；必须大于 0。', 'Override the model’s output token limit; must be positive.'],
  input_modalities: ['覆盖可接受的输入类型，每项填写一种，例如 text、image。', 'Override accepted input modalities, one per entry, such as text or image.'],
  output_modalities: ['覆盖可生成的输出类型，每项填写一种，例如 text、image。', 'Override output modalities, one per entry, such as text or image.'],
  capabilities: ['覆盖模型声明的能力列表；填写服务支持的能力标识。', 'Override declared capabilities using identifiers supported by the service.'],
  supports_client_tools: ['声明模型是否接受客户端工具定义和工具调用结果。', 'Declare whether the model accepts client tools and their results.'],
  supports_reasoning: ['声明模型是否支持推理能力，影响可选参数。', 'Declare reasoning support, affecting available parameters.'],
  default_reasoning_effort: ['未指定强度时使用的模型默认推理强度。', 'Default reasoning effort when no effort is specified.'],
  reasoning_efforts: ['把推理强度映射为上游使用的名称或 Token 预算。', 'Map reasoning effort values to upstream names or token budgets.'],
  default_policy: ['未单独指定代理策略的连接使用此策略。', 'Policy used when a connection inherits the default.'],
  artifact_policy: ['模型服务下载图片资源时使用的代理策略。', 'Proxy policy used when the provider service downloads image artifacts.'],
  policies: ['每项策略以唯一名称供其他配置引用，可选择环境变量、手动代理或直连。', 'Named policies can read the environment, use manual proxies or connect directly.'],
  proxy_policy: ['选择代理策略；inherit 使用模型服务默认策略。', 'Select a proxy policy; inherit uses the provider service default.'],
  http_url: ['手动策略下，访问 HTTP 目标使用的代理地址。', 'Proxy URL for HTTP destinations under a manual policy.'],
  https_url: ['手动策略下，访问 HTTPS 目标使用的代理地址。', 'Proxy URL for HTTPS destinations under a manual policy.'],
  all_url: ['手动策略下，未匹配专用代理时使用的通用代理地址。', 'Fallback proxy URL under a manual policy.'],
  type: ['选择凭据发送给目标服务的方式；需与目标接口要求一致。', 'How credentials are sent to the target service; match its API requirements.'],
  username: ['连接代理服务器所需的用户名。', 'Username required by the proxy server.'],
  password: ['连接代理服务器所需的密码；未编辑时保留原值。', 'Proxy password; untouched fields retain the existing value.'],
  first_byte_timeout_ms: ['请求发出后，等待上游首次响应的最长时间。', 'Maximum wait for the upstream’s first response after a request is sent.'],
  stream_idle_timeout_ms: ['流式响应中，两段数据之间允许空闲的最长时间。', 'Maximum idle gap between chunks in an upstream response stream.'],
  max_response_bytes: ['限制一次上游响应的总大小。', 'Maximum total size of one upstream response.'],
  max_event_bytes: ['限制流式响应中单个事件的大小。', 'Maximum size of an individual stream event.'],
  max_stream_events: ['限制一次流式响应可以包含的事件总数。', 'Maximum number of events in one response stream.'],
  max_error_body_bytes: ['上游返回错误时，最多保留多少响应正文用于排查。', 'Maximum upstream error-body content retained for diagnosis.'],
  model_list: ['单独配置查询可用模型的接口；未覆盖的身份验证沿用提供商设置。', 'Configure the model-catalog API; authentication inherits the provider unless overridden.'],
  image_edit_path: ['图片编辑接口的路径；部分图片协议可从生成接口路径推导。', 'Path for image editing; some image protocols can derive it from the generation path.'],
  headers: ['向此接口附加的 HTTP 请求头，按名称和值填写。', 'Additional HTTP headers sent to this API as name/value pairs.'],
  query: ['向此接口附加的 URL 查询参数，按名称和值填写。', 'Additional URL query parameters sent to this API as name/value pairs.'],
  codex: ['仅用于 Codex 协议的传输、账户和连接复用设置。', 'Transport, account and connection reuse settings for the Codex protocol.'],
  default_page_size: ['请求未指定数量时，默认读取多少个模型。', 'Default model count when a catalog request omits the page size.'],
  max_page_size: ['模型列表一次请求允许的最大数量，不能小于默认每页数量。', 'Maximum catalog page size; must be at least the default page size.'],
  generic: ['用于自定义 JSON 模型列表，把响应中的字段映射到模型属性。', 'Map fields in a custom JSON model catalog to model attributes.'],
  items_pointer: ['模型数组在完整响应中的 JSON Pointer，例如 /data。', 'JSON Pointer to the model array in the full response, such as /data.'],
  id_pointer: ['相对于每个模型对象的名称字段，例如 /id。', 'Model ID pointer relative to each model object, such as /id.'],
  next_cursor_pointer: ['下一页游标在完整响应中的位置，例如 /next_cursor。', 'Next-page cursor pointer in the full response, such as /next_cursor.'],
  cursor_query_parameter: ['请求下一页时，把游标放入哪个查询参数，例如 cursor。', 'Query parameter used to send the next-page cursor, such as cursor.'],
  limit_query_parameter: ['请求每页数量时使用的查询参数名称，例如 limit。', 'Query parameter for the requested page size, such as limit.'],
  strip_id_prefix: ['从返回的模型名称开头移除此前缀，例如 models/。', 'Prefix stripped from returned model IDs, such as models/.'],
  workspace_id: ['此 API 密钥所属的workspace ID，用于确定服务地址。', 'workspace ID associated with this API key; selects the service address.'],
  region: ['AWS 签名所使用的地区，需与目标服务一致。', 'AWS signing region; must match the target service.'],
  access_key_id: ['用于 AWS 签名的访问密钥 ID。', 'Access key ID used for AWS request signing.'],
  secret_access_key: ['与访问密钥 ID 配套的 AWS 密钥。', 'AWS secret key paired with the access key ID.'],
  session_token: ['使用临时 AWS 凭据时同时提供的会话令牌。', 'Session token supplied with temporary AWS credentials.'],
  credentials_path: ['后端机器上的 Google ADC 凭据文件路径。', 'Path to the Google ADC credentials file on the backend machine.'],
  transport: ['选择 SSE 或 WebSocket；auto 由协议实现决定传输方式。', 'Choose SSE, WebSocket, or let the protocol select with auto.'],
  account_id_source: ['从令牌声明读取账户 ID，或使用下方手动填写的值。', 'Read the account ID from token claims or use an explicit value.'],
  account_id: ['账户 ID 来源选择 explicit 时使用此值。', 'Account ID used when the source is explicit.'],
  originator: ['发送给 Codex 服务的客户端标识。', 'Client identifier sent to the Codex service.'],
  request_compression: ['选择关闭请求压缩、可用时压缩，或必须使用 zstd 压缩。', 'Disable compression, use zstd when available, or require zstd.'],
  websocket_connect_timeout_ms: ['建立 WebSocket 连接的最长等待时间。', 'Maximum wait to establish a WebSocket connection.'],
  websocket_idle_timeout_ms: ['WebSocket 连接等待新数据的空闲时间上限。', 'Maximum idle wait for new data on a WebSocket connection.'],
  websocket_cache_ttl_ms: ['已缓存的 WebSocket 连接可保留多久供后续请求复用。', 'Lifetime of cached WebSocket connections for reuse by later requests.'],
  websocket_cache_max_connections: ['最多保留多少个可复用的 WebSocket 连接。', 'Maximum cached WebSocket connections.'],
  session_affinity_max_bytes: ['限制随请求携带的会话关联信息大小。', 'Maximum session-affinity payload sent with a request.'],
  fallback_to_sse_before_first_event: ['WebSocket 在首个事件到达前失败时，允许改用 SSE；已开始输出后不会重放。', 'Allow SSE fallback if WebSocket fails before the first event; output already started is not replayed.'],
  supports_developer_role: ['目标协议是否接受 developer 角色的消息。', 'Whether the target protocol accepts messages with the developer role.'],
  supports_stream_usage: ['目标协议是否支持在流式响应中返回用量统计。', 'Whether the target protocol supports usage reporting in response streams.'],
  max_tokens_field: ['指定请求中控制输出 Token 上限的字段名称。', 'Request field used to specify the output token limit.'],
  reasoning_output_field: ['指定从哪个响应字段读取思考内容；none 表示没有独立字段。', 'Response field containing reasoning; none means no separate field.'],
  reasoning_replay: ['决定后续请求是否回传模型之前的思考内容。', 'When previous reasoning content is included in subsequent requests.'],
  tool_arguments_wire: ['目标接口以 JSON 字符串、对象，或两种形式接收工具参数。', 'Whether the API uses JSON strings, objects, or both for tool arguments.'],
  assistant_prefill_field: ['目标接口使用哪个选项表示助手消息预填充；none 表示不使用。', 'Option used for assistant-message prefill; none disables it.'],
  prompt_cache_key: ['声明目标接口是否接受或要求提示词缓存标识。', 'Declare whether the target accepts or requires a prompt cache key.'],
  unknown_finish_reason: ['上游返回未知结束原因时，保留为未知状态或明确报错。', 'Preserve an unrecognized finish reason as unknown, or report an error.'],
  request_path: ['输入 Token 计数接口的请求路径。', 'Request path for input token counting.'],
  may_bill: ['标明提供商的计数请求可能收费，供调用方识别。', 'Declare that provider-side counting may be billable.'],
  timeout_ms: ['一次输入 Token 计数请求的最长等待时间。', 'Maximum duration of one input-token count request.'],
  allow_unverified_overrides: ['允许使用未由命名协议确认的覆盖项；目标服务仍可能拒绝请求。', 'Permit overrides not verified by the named dialect; the target may still reject them.'],
  contract_version: ['协议扩展配置的契约版本，当前使用 1。', 'Contract version of the dialect configuration; currently 1.'],
};
const paths: Record<string, Help> = {
  'wishd/auth': ['验证访问 wishd 的客户端身份；令牌授权可以访问完整 API。', 'Authenticate clients accessing wishd; the token grants access to its full API.'],
  'providerd/auth': ['验证访问模型服务的客户端，包括 wishd 的内部连接。', 'Authenticate provider-service clients, including the connection from wishd.'],
  'wishd/provider_client/base_url': ['填写 wish-providerd 的地址，例如 http://127.0.0.1:9781。', 'Address of wish-providerd, such as http://127.0.0.1:9781.'],
  'wishd/provider_client/proxy_policy': ['direct 直连；environment 读取代理环境变量；手动代理填写 manual:http://代理地址。', 'Use direct, environment, or manual:http://proxy-address.'],
  'streaming/enabled': ['开启后边生成边显示回复；关闭后不推送生成过程中的内容。', 'Deliver reply content as it is generated; disable live generation updates when off.'],
  'compaction/enabled': ['允许后台准备压缩后的上下文；关闭后不自动进行上下文压缩。', 'Allow background preparation of compacted context; disable automatic compaction when off.'],
  'context_measurement/enabled': ['启用上下文 Token 用量测量功能。', 'Enable measurement of context token usage.'],
  'storage/cold/enabled': ['自动压缩闲置会话数据库以节省磁盘，再次访问时恢复。', 'Automatically compress idle session databases and restore them when accessed.'],
  'retry/circuit_breaker/enabled': ['请求频繁失败时暂停调用，再探测恢复；关闭后只使用普通重试策略。', 'Pause repeated failures and probe for recovery; otherwise use ordinary retries only.'],
  'retry/model': ['模型请求失败后的尝试次数与等待时间。', 'Attempt counts and delays after model-request failures.'],
  'shell/background_notifications/max_command_bytes': ['后台执行通知中最多复制多少命令文本，完整命令仍保存在执行记录中。', 'Command text copied into a completion notification; the execution record retains the full command.'],
  'providerd/providers/*/enabled': ['决定此提供商是否作为可用提供商对外提供。', 'Expose this instance as an available provider.'],
  'providerd/providers/*/input_count/mode': ['向提供商查询精确计数、使用本地计数，或禁用计数。', 'Use provider preflight counting, local counting, or disable counting.'],
  'providerd/proxy/policies/*/source': ['environment 读取进程代理环境变量；manual 使用下方地址；disabled 直接连接。', 'environment reads process proxy variables; manual uses configured URLs; disabled connects directly.'],
  'account_observation/bindings/*/credential/source': ['目前使用 env，从后端进程环境变量读取凭据。', 'Use env to read credentials from the backend process environment.'],
  'account_observation/bindings/*/credential/name': ['填写保存凭据的环境变量名称，不是凭据本身。', 'Environment variable name containing the credential, not the credential itself.'],
  'account_observation/endpoints/*/proxy_policy': ['direct 直连；environment 读取代理环境变量；也可使用 manual:http://代理地址。', 'Use direct, environment, or manual:http://proxy-address.'],
};
export function helpFor(path: string[]): Help | undefined {
  const normalized = path.map((part, i) => /^\d+$/.test(part) || path[i - 1] === 'models' ? '*' : part).join('/');
  if (paths[normalized]) return paths[normalized];
  const key = path.at(-1)!;
  const parent = path.at(-2);
  // Map keys are user-defined names, never schema field names.
  if (parent === 'credentials') return fields[key] || fields.credentials;
  if (parent && ['headers', 'query', 'reasoning_efforts'].includes(parent)) return fields[parent];
  if (parent === 'models') return fields.models;
  if (/^\d+$/.test(key)) return fields[parent!];
  if (key === 'mode' && parent === 'auth') return ['不使用表示不验证令牌；访问令牌模式要求客户端携带有效令牌。', 'none disables token checks; bearer requires a valid token on client requests.'];
  if (key === 'auth') return ['配置此连接如何向目标服务验证身份。', 'Configure authentication for this connection to the target service.'];
  if (key === 'token') return ['访问令牌模式使用的凭据；未编辑时保留现有值。', 'Credential used for bearer authentication; untouched fields retain the existing value.'];
  if (key === 'name' && parent === 'auth') return ['携带凭据的请求头或查询参数名称。', 'Name of the header or query parameter carrying the credential.'];
  if (key === 'value' && parent === 'auth') return ['填入上述请求头或查询参数的凭据值。', 'Credential value sent in the configured header or query parameter.'];
  if (key.endsWith('_pointer') && parent === 'generic') return ['相对于每个模型对象的 JSON Pointer；移除此项则不映射该属性。', 'JSON Pointer relative to each model object; remove to leave the attribute unmapped.'];
  return fields[key];
}
