#!/usr/bin/env python3
"""Build the variable Latin fonts with their weights calibrated to the Chinese fonts beside them.

A CSS weight sets both fonts of a line, but their stems differ: Montserrat at 600 is a third
heavier than Sarasa Gothic SC's SemiBold. This rewrites each @fontsource font's avar so a CSS
weight lands on the design whose vertical stem matches its partner's, as measured by
tools/measure-font-weights.py, and writes the files and @font-face rules the app loads instead
of @fontsource's own CSS into src/generated/fonts/ (run by tools/fonts.py). The axis keeps its range; weights between the measured ones follow
linearly.

Requires Python fontTools + Brotli and ./pnpmw install.
"""
from pathlib import Path
import re
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'src/generated/fonts'
FONTS = {
    # Against Sarasa Gothic SC: Regular, Regular grown to a medium, SemiBold, Bold.
    'montserrat': {'family': 'Montserrat Variable', 'styles': ['index.css'], 'weights': {400: 409, 500: 447, 600: 483, 700: 577}},
    # Against Noto Serif SC, which follows the CSS weight itself.
    'bitter': {'family': 'Bitter Variable', 'styles': ['index.css', 'wght-italic.css'], 'weights': {400: 348, 500: 392, 600: 454, 700: 555}},
}


def between(x, points):
    """Piecewise-linear interpolation through sorted (x, y) points."""
    for (x0, y0), (x1, y1) in zip(points, points[1:]):
        if x <= x1:
            return y0 if x1 == x0 else y0 + (y1 - y0) * (x - x0) / (x1 - x0)
    return points[-1][1]


def calibrate(font, weights):
    """Sends each CSS weight to its calibrated design weight through the font's avar."""
    axis = next(axis for axis in font['fvar'].axes if axis.axisTag == 'wght')
    low, default, high = axis.minValue, axis.defaultValue, axis.maxValue
    normalize = lambda w: (w - default) / (high - default) if w >= default else (w - default) / (default - low)
    denormalize = lambda n: default + n * (high - default) if n >= 0 else default + n * (default - low)
    user = sorted({low: low, high: high, **weights}.items())
    design = [(d, u) for u, d in user]
    segments = font['avar'].segments['wght']
    old = sorted(segments.items())
    # Both maps are piecewise linear, so their composition is exact at the union of their corners.
    corners = {normalize(u) for u, _ in user} | {normalize(between(denormalize(n), design)) for n, _ in old}
    segments.clear()
    segments.update({n: between(normalize(between(denormalize(n), user)), old) for n in sorted(corners)})
    segments.update({-1.0: -1.0, 0.0: 0.0, 1.0: 1.0})


def main():
    for key, config in FONTS.items():
        package = ROOT / 'node_modules/@fontsource-variable' / key
        out = OUT / key
        out.mkdir(parents=True, exist_ok=True)
        rules = []
        for style in config['styles']:
            css = (package / style).read_text()
            for block in re.findall(r'@font-face\s*\{(.*?)\}', css, re.S):
                name = re.search(r'url\(\./files/([^)]+)\)', block).group(1)
                font = TTFont(package / 'files' / name)
                calibrate(font, config['weights'])
                font.save(out / name)
                italic = re.search(r'font-style:\s*(\w+)', block).group(1)
                ranges = re.search(r'unicode-range:\s*([^;]+)', block).group(1)
                rules.append(f"@font-face {{ font-family: '{config['family']}'; font-style: {italic}; font-display: swap; font-weight: 100 900; src: url('./{key}/{name}') format('woff2-variations'); unicode-range: {ranges}; }}\n")
        (OUT / f'{key}.css').write_text('/* Generated by tools/build-latin-fonts.py; OFL notice in public/licenses. */\n' + ''.join(rules))
        print(f'{key}: {len(rules)} files, CSS weight to design weight {config["weights"]}')


if __name__ == '__main__':
    main()
