#!/usr/bin/env python3
"""Build local CJK WOFF2 shards from pinned official font archives.

Requires Python fontTools + Brotli and 7z. Download the archive into .cache/fonts
from the URL in src/assets/fonts/<font>/source.json, then run this script.
Uses the existing Noto Serif SC unicode partitions for common CJK characters;
remaining glyphs are emitted in disjoint groups, preserving source coverage.
"""
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path
import argparse
import hashlib
import json
import re
import subprocess
from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
FONTS = {
    'sarasa': {'version':'1.0.41', 'archive':'SarasaGothicSC-TTF-Unhinted-1.0.41.7z', 'family':'Sarasa Gothic SC', 'prefix':'sarasa-sc', 'names':['SarasaGothicSC-Regular.ttf','SarasaGothicSC-SemiBold.ttf'], 'release':'https://github.com/be5invis/Sarasa-Gothic/releases/download/v1.0.41/'},
    'maple': {'version':'7.9', 'archive':'MapleMono-NF-CN-unhinted.zip', 'family':'Maple Mono NF CN', 'prefix':'maple-mono', 'names':['MapleMono-NF-CN-Regular.ttf','MapleMono-NF-CN-SemiBold.ttf'], 'release':'https://github.com/subframe7536/maple-font/releases/download/v7.9/'},
}


def unicode_ranges(points):
    runs = []
    start = end = points[0]
    for point in points[1:]:
        if point == end + 1:
            end = point
        else:
            runs.append(f'U+{start:X}' if start == end else f'U+{start:X}-{end:X}')
            start = end = point
    runs.append(f'U+{start:X}' if start == end else f'U+{start:X}-{end:X}')
    return ','.join(runs)


def build(job):
    source, weight, index, points, out, family, prefix, key = job
    font = TTFont(source, recalcTimestamp=False)
    options = subset.Options()
    options.flavor = 'woff2'
    options.recalc_timestamp = False
    worker = subset.Subsetter(options=options)
    worker.populate(unicodes=points)
    worker.subset(font)
    font.flavor = 'woff2'
    name = f'{prefix}-{weight}-{index}.woff2'
    font.save(Path(out) / name)
    font.close()
    ranges = unicode_ranges(points)
    return f"@font-face {{ font-family: '{family}'; font-style: normal; font-weight: {weight}; font-display: swap; src: url('../assets/fonts/{key}/{name}') format('woff2'); unicode-range: {ranges}; }}\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('font', choices=FONTS)
    key = parser.parse_args().font
    config = FONTS[key]
    archive = ROOT / '.cache/fonts' / config['archive']
    out = ROOT / 'src/assets/fonts' / key
    out.mkdir(parents=True, exist_ok=True)
    if key == 'maple':
        expected = archive.with_suffix('.sha256').read_text().strip()
        assert hashlib.sha256(archive.read_bytes()).hexdigest() == expected, 'Official archive checksum mismatch'

    destination = ROOT / '.cache/fonts' / (key+'-source')
    names = config['names']
    subprocess.run(['7z', 'e', '-y', str(archive), '-o'+str(destination), *names], check=True, stdout=subprocess.DEVNULL)
    css = (ROOT / 'node_modules/@fontsource-variable/noto-serif-sc/index.css').read_text()
    partitions = []
    for value in re.findall(r'unicode-range:\s*([^;]+)', css):
        points = set()
        for item in value.split(','):
            limits = item.strip()[2:].split('-')
            points.update(range(int(limits[0],16),int(limits[-1],16)+1))
        partitions.append(points)
    jobs = []
    for weight, name in zip((400,600), names):
        source = destination / name
        with TTFont(source) as font:
            remaining = set(font.getBestCmap())
        groups = []
        for partition in partitions:
            points = remaining & partition
            if points:
                groups.append(sorted(points))
                remaining -= points
        remainder = sorted(remaining)
        groups += [remainder[i:i+512] for i in range(0,len(remainder),512)]
        jobs.extend((str(source),weight,i,points,str(out),config['family'],config['prefix'],key) for i,points in enumerate(groups))
    with ProcessPoolExecutor(max_workers=6) as pool:
        rules = list(pool.map(build,jobs))
    (ROOT/f'src/styles/{key}.css').write_text('/* Generated by tools/build-cjk-fonts.py; OFL notice in public/licenses. */\n'+''.join(rules))
    (out/'source.json').write_text(json.dumps({'version':config['version'],'url':config['release']+config['archive'],'archive_sha256':hashlib.sha256(archive.read_bytes()).hexdigest(),'weights':[400,600],'shards':len(jobs),'license':'OFL-1.1'},indent=2)+'\n')
    print(f'Built {len(jobs)} disjoint WOFF2 shards ({sum(p.stat().st_size for p in out.glob("*.woff2"))} bytes).')

if __name__ == '__main__':
    main()
