// Build-time tool: fetch a Lucide icon subset and generate the vendored icon
// module (webroot/app/ui/icons.js). Network is used HERE ONLY; the built app
// never fetches icons at runtime. Rerun: node tools/fetch-icons.mjs
import { writeFile, mkdir } from 'node:fs/promises';

const NAMES = [
  'message-circle','chart-column','settings','search','plus','info','history',
  'ellipsis-vertical','ellipsis','arrow-left','arrow-up','image','image-plus','send','square',
  'sun','moon','x','chevron-down','chevron-left','chevron-right','chevron-up',
  'loader-circle','circle-alert','circle-check','check','terminal','brain','wrench',
  'copy','refresh-cw','trash-2','pencil','languages','sparkles','paperclip',
  'panel-left','pin','message-square-plus','database','gauge','bell','bell-ring','keyboard',
  'accessibility','wifi-off','circle-dot','list','list-tree','external-link','download',
  'clock','bot','user','corner-down-left','split','archive','layers','key-round',
  'shield','plug','cpu','file-json','file-down','search-code','settings-2','monitor',
  'smartphone','app-window','toggle-left','log-out','zap','folder','hard-drive',
  'activity','calendar','hash','filter','maximize-2','minimize-2','pause','play',
];
// historical aliases tried when the primary name 404s (lucide renames)
const ALIASES = {
  'chart-column': ['bar-chart-3'], 'ellipsis-vertical': ['more-vertical'],
  'ellipsis': ['more-horizontal'], 'loader-circle': ['loader-2'],
  'circle-alert': ['alert-circle'], 'circle-check': ['check-circle'],
  'circle-dot': ['dot'], 'list-tree': ['list-tree'],
};

const inner = (svg) =>
  svg.replace(/<!--[\s\S]*?-->\s*/g, '')      // strip license comments
     .replace(/^\s*<svg[^>]*>/, '')            // strip wrapper tag
     .replace(/<\/svg>\s*$/, '')
     .trim();
const attrs = (svg) => (svg.replace(/<!--[\s\S]*?-->\s*/g, '').match(/^\s*<svg[^>]*>/) || [''])[0];

const out = {};
for (const name of NAMES) {
  const candidates = [name, ...(ALIASES[name] || [])];
  let ok = false;
  for (const c of candidates) {
    const r = await fetch(`https://unpkg.com/lucide-static@0.544.0/icons/${c}.svg`);
    if (!r.ok) continue;
    const svg = await r.text();
    out[name] = { attrs: attrs(svg), inner: inner(svg) };
    ok = true;
    break;
  }
  if (!ok) console.warn(`MISS ${name}`);
}
const banner = `// AUTO-GENERATED by tools/fetch-icons.mjs — Lucide 0.544.0 (ISC license).
// Vendored subset; the app has no runtime icon downloads.
export const ICONS = ${JSON.stringify(out, null, 0)};
export const ICON_NAMES = Object.keys(ICONS);
`;
await mkdir(new URL('../webroot/app/ui/', import.meta.url), { recursive: true });
await writeFile(new URL('../webroot/app/ui/icons.js', import.meta.url), banner);
console.log(`icons: ${Object.keys(out).length}/${NAMES.length}`);
