// GENERATED by tools/sw-manifest.mjs — do not edit by hand.
// App-shell precache: the full module graph, versioned by content hash.
//   · cache-first for shell files (immutable per version; updates arrive as
//     a NEW service worker — never a mixed in-place mutation);
//   · activation only after the user confirms (SKIP_WAITING message from
//     the update prompt) — no mixed versions;
//   · /wishd-api/* and /providerd-api/* and every non-GET: always live,
//     never cached;
//   · only caches in THIS app's namespace (wish-web-shell-*) are managed.
const VERSION = 'wish-web-shell-63b4d362b4c4d3be';
const SHELL = [
  "/",
  "/app-icons/icon-192.png",
  "/app-icons/icon-512.png",
  "/app-icons/maskable-512.png",
  "/app/core/api/client.js",
  "/app/core/api/endpoints.js",
  "/app/core/api/sse.js",
  "/app/core/bus.js",
  "/app/core/config.js",
  "/app/core/i18n/en.js",
  "/app/core/i18n/index.js",
  "/app/core/i18n/zh.js",
  "/app/core/state/chatSlice.js",
  "/app/core/state/prefsSlice.js",
  "/app/core/state/reactive.js",
  "/app/core/state/sessionsSlice.js",
  "/app/core/state/statsSlice.js",
  "/app/core/state/syncSlice.js",
  "/app/core/theme/index.js",
  "/app/core/util/fmt.js",
  "/app/main.js",
  "/app/platform/browser/app.js",
  "/app/platform/browser/fs.js",
  "/app/platform/browser/index.js",
  "/app/platform/browser/notify.js",
  "/app/platform/browser/share.js",
  "/app/platform/browser/storage.js",
  "/app/platform/index.js",
  "/app/ui/applyTokens.js",
  "/app/ui/components/button.js",
  "/app/ui/components/copyable.js",
  "/app/ui/components/icon.js",
  "/app/ui/components/markdown.js",
  "/app/ui/components/menu.js",
  "/app/ui/components/modal.js",
  "/app/ui/components/sheet.js",
  "/app/ui/components/spinner.js",
  "/app/ui/components/toast.js",
  "/app/ui/components/vlist.js",
  "/app/ui/features/registry.js",
  "/app/ui/features/selftest/index.js",
  "/app/ui/features/selftest/view.js",
  "/app/ui/features/sessions/chat.js",
  "/app/ui/features/sessions/composer.js",
  "/app/ui/features/sessions/entry.js",
  "/app/ui/features/sessions/grouping.js",
  "/app/ui/features/sessions/index.js",
  "/app/ui/features/sessions/info.js",
  "/app/ui/features/sessions/list.js",
  "/app/ui/features/sessions/manage.js",
  "/app/ui/features/sessions/models.js",
  "/app/ui/features/sessions/modelsettings.js",
  "/app/ui/features/sessions/newsession.js",
  "/app/ui/features/sessions/resize.js",
  "/app/ui/features/sessions/search.js",
  "/app/ui/features/settings/index.js",
  "/app/ui/features/settings/view.js",
  "/app/ui/features/stats/index.js",
  "/app/ui/features/stats/view.js",
  "/app/ui/h.js",
  "/app/ui/hooks.js",
  "/app/ui/icons.js",
  "/app/ui/index.js",
  "/app/ui/layout/appshell.js",
  "/app/ui/live.js",
  "/app/ui/notify.js",
  "/app/ui/router.js",
  "/app/ui/shortcuts.js",
  "/index.html",
  "/manifest.webmanifest",
  "/styles/base.css",
  "/styles/components.css",
  "/styles/features.css",
  "/styles/layout.css",
  "/styles/tokens.css",
  "/vendor/htm/htm.module.js",
  "/vendor/preact/hooks.module.js",
  "/vendor/preact/preact.module.js"
];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(VERSION).then((c) => c.addAll(SHELL)));
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    for (const k of await caches.keys()) {
      if (k.startsWith('wish-web-shell-') && k !== VERSION) await caches.delete(k);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('message', (e) => {
  if (e.data?.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url);
  if (e.request.method !== 'GET') return;                    // mutations: live
  if (url.pathname.startsWith('/wishd-api/') || url.pathname.startsWith('/providerd-api/')) return;  // API: live only
  if (url.origin !== location.origin) return;
  const isShell = SHELL.includes(url.pathname)
    || (e.request.mode === 'navigate' && (url.pathname === '/' || url.pathname === '/index.html'));
  if (!isShell) return;                                      // everything else: live
  e.respondWith((async () => {
    const cache = await caches.open(VERSION);
    const hit = await cache.match(url.pathname === '/' ? '/index.html' : e.request, { ignoreSearch: true });
    if (hit) return hit;
    const res = await fetch(e.request);
    if (res.ok) cache.put(e.request, res.clone());
    return res;
  })());
});
